version: "3.8"
services:

## Run from the directory that has both the api and the external api

  server:
    build: .
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: 1024M

  external-api:
    build:
      context: ../aseca-external-api
      dockerfile: Dockerfile
    ports:
      - '8081:8081'

  postgres:
    image: postgres:10.3
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: